### ISSUE TITLE
Extension doesn't work

### ISSUE THREAD

**Issue by gosteev** [jianweichuah/miniyoutube#1]
Tried to disable my other extensions - same result.
windows 8.1 x64, chrome v 40.0.2214.115 m (latest)

**Comment by jianweichuah** [comment]
Hey @mjrev, thanks for letting me know! Do you mind elaborating more on the steps to reproduce? Like the YouTube URL you tried and which part is not working (screen doesn't appear)?

**Comment by jianweichuah** [comment]
I just tried it on my friend's laptop with running windows 8.1 x64, chrome v 40.0.2214.115 and it's working fine. Please let me know the exact steps you took.

**Comment by gosteev** [comment]
there are no floating window at all. the last time i tried i did next things - disabled all extensions except miniyoutube, and in new window open up this video http://www.youtube.com/watch?v=WbIVV9cVveo or any other.

also i tried in incognito mode, but no result

**Comment by jianweichuah** [comment]
It's weird. I tried again with the exact URL provided and with other extensions for YouTube like AdBlock on and it's working fine.
Could you please do me a favor and follow these steps:
1. Make sure Mini YouTube is enabled.
2. Open up Developer Tools and go to the Console tab.
3. Open up any YouTube video URL.
4. Scroll down to the comment section.
5. See if there's any error in the Console.
6. Take a screenshot of it.

Like this:
![screen shot 2015-02-23 at 3 22 14 pm](https://cloud.githubusercontent.com/assets/1463489/6336321/c5ed2c50-bb6f-11e4-942a-44ce1dbfadab.png)

That'd be really helpful.
Thank you :)

**Comment by gosteev** [comment]
of course. here:
![image](https://cloud.githubusercontent.com/assets/6203574/6336438/a7c7b800-bbb3-11e4-9fe1-fef4dff72a5a.png)

ps. i also used "streamus" and "be limitless" one time :yum:

**Comment by jianweichuah** [comment]
That's fast. Thank you!
The errors I see in the screenshot don't seem to be related to Mini YouTube.
I get them even when Mini YouTube is working for me.
![screen shot 2015-02-23 at 3 36 39 pm](https://cloud.githubusercontent.com/assets/1463489/6336617/dc01a942-bb71-11e4-9abb-4eba6171c0ce.png)

Do you see any suspicious errors that might be related when you scroll up?

PS: Yeah they're pretty good!

**Comment by gosteev** [comment]
okay, now it is working. i really did nothing except putting my PC to sleep on night.
BUT there is another person who faced the same problem as i. i will try to work out something, and post here afterwards

**Comment by jianweichuah** [comment]
Awesome! This is really weird then. Hopefully we can find a way to fix it :smiley:
Thanks a lot man. Really appreciate your help and your patience!

**Comment by gosteev** [comment]
since my last post i tried to do some _tests_ because it broke down. again. :frowning: and i can't really find out what causes this. such great extension and such lame user. :sweat_smile: anyway, i moved to firefox for some time, do you plan to port app to FF?

**Comment by jianweichuah** [comment]
Might it be the problem with Flash? I just bumped into a Flash video a few hours ago and pushed an update to show a message saying "Flash videos not supported" if it's running flash.

Yea, I'm gonna port it over to FF next :smile:

**Comment by jianweichuah** [comment]
YouTube uses Flash for FF. Can't reuse what I do for Chrome and I'm pretty busy recently. The FF version won't be so soon.
