### ISSUE TITLE
Not available on Chrome Web Store

### ISSUE THREAD

**Issue by neonoafs** [jianweichuah/miniyoutube#16]
Cant download it anymore from Web Store. Does Chrome ditched it?
![deepin screenshot_20180714231439](https://user-images.githubusercontent.com/29025241/42729839-d135ae22-87bb-11e8-8c57-a8373d6ef1ba.png)

**Comment by jianweichuah** [comment]
Hmm let me check with the chrome team.

**Comment by jianweichuah** [comment]
Should be back up https://chrome.google.com/webstore/detail/mini-y/acphfpihfjpgnihkgelafhmjeoodbehp. Thanks for reporting :)

**Comment by MesaBlack** [comment]
it's gone again.
