### ISSUE TITLE
Extension doesn't remember preset location

### ISSUE THREAD

**Issue by sguergachi** [jianweichuah/miniyoutube#2]
Disabled all extention except mini youtube.
- Open video and scroll down
- Reposition mini youtube
- Refresh page
- Scroll down again
- Mini youtube is back to it's default location.

**Comment by jianweichuah** [comment]
@sguergachi Hey, thanks for reporting! It's actually intentional to reset all the settings at every page refresh because I save those parameters in JavaScript. I was afraid if we saved it to the user's account or the browser, the settings would not be valid anymore if the user resizes the screen. It should work if you watch the next video without refreshing.

**Comment by sguergachi** [comment]
My page always refreshes when I click on another video from a playing video.

**Comment by jianweichuah** [comment]
Could you try something out for me?
1. Scroll down, configure your screen (place and size etc).
2. Scroll up.
3. Click on another video.
4. Scroll down and you should see the screen at the previous location with the previous size.

**Comment by sguergachi** [comment]
that's what I did, It resets it for me.

**Comment by jianweichuah** [comment]
Really? The part where you scroll up to put the screen back to the player is where the settings are saved.
If you have done that and it doesn't work, I guess I would have to save it in the browser then.

Can you confirm that?

**Comment by sguergachi** [comment]
Well, I turned my extensions back on, so that could be part of the issue but yes. After multiple attempts it doesn't keep track of it.

You could store both the current screen resolution along with the miniyoutube screen position and if screen res has changed since last time then just use default position.

**Comment by jianweichuah** [comment]
Alright. Thanks for letting me know about this. I'll work on it after my exams and update the status of this ticket when it's done :smile: 
Thanks for using Mini YouTube!

**Comment by jianweichuah** [comment]
Hey @sguergachi I've just released an update to add in this functionality (v1.2.1).
You'll see something like this:
![screen shot 2015-03-02 at 4 31 51 pm](https://cloud.githubusercontent.com/assets/1463489/6451179/bbbc127e-c0fa-11e4-937f-1f7a961aeb7c.png)

When you click on the pin button, the position and size of the screen will be saved.
It will then be used for future videos and even after you restart Chrome.

Your extension should be updated automatically soon.
Try it out and let me know how you think.
If it's good I'll close this ticket :smile:

**Comment by sguergachi** [comment]
Seems to work. Thanks!

-Sammy Guergachi
On 3/2/2015 4:47:12 PM, Jian Wei Chuah notifications@github.com wrote:
Hey @sguergachi [https://github.com/sguergachi] I've just released an update to add in this functionality (v1.2.1).
You'll see something like this:
[screen shot 2015-03-02 at 4 31 51 pm] [https://cloud.githubusercontent.com/assets/1463489/6451179/bbbc127e-c0fa-11e4-937f-1f7a961aeb7c.png]
When you click on the pin button, the position and size of the screen will be saved.
It will then be used for future videos and even after you restart Chrome.
Your extension should be updated automatically soon.
Try it out and let me know how you think.
If it's good I'll close this ticket [:smile:]
&mdash;

**Comment by jianweichuah** [comment]
Awesome. Thanks for your support again! Please leave a review/rating if you like it :smiley:
